"""Add status column to service_ticket table

Revision ID: c25e2a35e12e
Revises: 0e9d1b35a5b4
Create Date: 2025-11-17 14:52:33.719082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c25e2a35e12e'
down_revision = '0e9d1b35a5b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_ticket', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
